# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo_MovieDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'youtube-ios-player-helper'
  pod 'ESPullToRefresh'

end
